import { supabase } from "@/lib/supabase";

// Type definition for Tarjeta (Card)
export interface Tarjeta {
  uuid: string;
  title: string;
  content: string;
  section: string;
  created_by: string;
  updated_by: string;
  created_at: string;
  deleted_at?: string | null;
}

/**
 * Fetches all cards for a specific section that haven't been deleted
 * @param sectionName - The section name to filter by
 * @returns Array of cards or empty array if none found
 */
export async function getCardsBySection(sectionName: string): Promise<Tarjeta[]> {
  try {
    const { data, error } = await supabase
      .from('cards')
      .select('*')
      .eq('section', sectionName)
      .is('deleted_at', null)
      .order('created_at', { ascending: false });

    if (error) {
      console.error(`Error fetching cards for section "${sectionName}":`, error.message);
      throw new Error(`Failed to fetch cards: ${error.message}`);
    }

    return data || [];
  } catch (err) {
    console.error('Unexpected error in getCardsBySection:', err);
    throw err;
  }
}

/**
 * Creates a new card in the database
 * @param cardData - Partial card data (uuid will be auto-generated by DB)
 * @returns The newly created card or null if failed
 */
export async function createCard(cardData: Partial<Tarjeta>): Promise<Tarjeta | null> {
  try {
    const { data, error } = await supabase
      .from('cards')
      .insert([cardData])
      .select()
      .single();

    if (error) {
      console.error('Error creating card:', error.message);
      throw new Error(`Failed to create card: ${error.message}`);
    }

    return data;
  } catch (err) {
    console.error('Unexpected error in createCard:', err);
    throw err;
  }
}

/**
 * Updates an existing card by its UUID
 * @param uuid - The unique identifier of the card
 * @param updates - Partial card data to update
 * @returns The updated card or null if failed
 */
export async function updateCard(uuid: string, updates: Partial<Tarjeta>): Promise<Tarjeta | null> {
  try {
    const { data, error } = await supabase
      .from('cards')
      .update(updates)
      .eq('uuid', uuid)
      .select()
      .single();

    if (error) {
      console.error(`Error updating card with uuid "${uuid}":`, error.message);
      throw new Error(`Failed to update card: ${error.message}`);
    }

    return data;
  } catch (err) {
    console.error('Unexpected error in updateCard:', err);
    throw err;
  }
}

/**
 * Performs a logical delete on a card by setting delete_at timestamp
 * @param uuid - The unique identifier of the card to delete
 * @returns The deleted card with updated delete_at or null if failed
 */
export async function deleteCard(uuid: string): Promise<Tarjeta | null> {
  try {
    const { data, error } = await supabase
      .from('cards')
      .update({ deleted_at: new Date().toISOString() })
      .eq('uuid', uuid)
      .select()
      .single();

    if (error) {
      console.error(`Error deleting card with uuid "${uuid}":`, error.message);
      throw new Error(`Failed to delete card: ${error.message}`);
    }

    return data;
  } catch (err) {
    console.error('Unexpected error in deleteCard:', err);
    throw err;
  }
}